import "dotenv/config";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import rateLimit from "express-rate-limit";
import { v4 as uuidv4 } from "uuid";

import { analyzeMessage, pingGemini } from "./ai/gemini.js";
import { runGuardrails, sanitizeAIOutput } from "./guardrails/guardrails.js";
import { applyDecisionRules } from "./decision/decisionEngine.js";
import { runEvaluation } from "./evaluation/evaluator.js";
import { db } from "./database.js";

const app = express();
const PORT = process.env.PORT || 3001;

// ─── Middleware ───────────────────────────────────────────────────────────────
app.use(helmet());
app.use(cors({
  origin: true,
  credentials: true,
  methods: ["GET", "POST"],
  allowedHeaders: ["Content-Type"],
}));
app.use(express.json({ limit: "1mb" }));
app.use(morgan("dev"));

// ─── Rate limiting ────────────────────────────────────────────────────────────
const apiLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 120,
  message: { error: "Too many requests. Please slow down." },
});
app.use("/api/", apiLimiter);

// ─── API Routes ───────────────────────────────────────────────────────────────

/**
 * Real-Time Gemini AI Triage Endpoint
 * All analysis is dynamically generated by Google Gemini 2.0 Flash LLM.
 */
app.post("/api/analyze", async (req, res) => {
  const requestId = uuidv4();
  const requestStart = Date.now();

  try {
    const { message } = req.body;

    if (!message || typeof message !== "string") {
      return res.status(400).json({
        error: "Invalid request. 'message' string is required.",
        requestId,
      });
    }

    // Layer 1 & 2: Security Guardrails
    const guardrailResult = runGuardrails(message);

    if (guardrailResult.blocked && !guardrailResult.adversarial) {
      const blockedDecision = {
        category: "OUT_OF_SCOPE",
        priority: "P3",
        summary: guardrailResult.reason || "Message blocked by guardrails.",
        suggested_action: "Review guardrail flags and respond appropriately.",
        needs_human: true,
        confidence: 0.1,
        language: "Unknown",
        sentiment: "NEUTRAL",
        risk_level: guardrailResult.risk,
        issues: [],
        is_multi_issue: false,
        is_adversarial: guardrailResult.adversarial,
        is_out_of_scope: true,
        escalation_reason: guardrailResult.reason,
        reasoning_summary: `Blocked by guardrail: ${guardrailResult.flags.join(", ")}`,
        outcome: "BLOCKED_UNSAFE",
        outcome_label: "Blocked — Safety Check Failed",
        decision_overrides: [],
        decision_rules_applied: ["GUARDRAIL_BLOCK"],
      };

      const totalLatency = Date.now() - requestStart;
      db.insertTriage({ id: requestId, timestamp: new Date().toISOString(), message, decision: blockedDecision, latency_ms: totalLatency });

      return res.json({
        requestId,
        decision: blockedDecision,
        guardrails: { blocked: guardrailResult.blocked, adversarial: guardrailResult.adversarial, risk: guardrailResult.risk, flags: guardrailResult.flags },
        latency_ms: totalLatency,
        token_usage: null,
      });
    }

    // Layer 3: Google Gemini 2.0 Flash LLM Model Call
    const messageToAnalyze = guardrailResult.sanitized || message;
    const aiResult = await analyzeMessage(messageToAnalyze);

    // Layer 4 & 5: Sanitization and Business Decision Engine
    const sanitizedDecision = sanitizeAIOutput(aiResult.decision);
    if (guardrailResult.adversarial) {
      sanitizedDecision.is_adversarial = true;
    }

    const finalDecision = applyDecisionRules(sanitizedDecision, guardrailResult);
    const totalLatency = Date.now() - requestStart;

    // Persist real AI decision into SQLite Database
    db.insertTriage({
      id: requestId,
      timestamp: new Date().toISOString(),
      message,
      decision: finalDecision,
      latency_ms: totalLatency,
    });

    res.json({
      requestId,
      decision: finalDecision,
      guardrails: {
        blocked: guardrailResult.blocked,
        adversarial: guardrailResult.adversarial,
        risk: guardrailResult.risk,
        flags: guardrailResult.flags,
      },
      latency_ms: totalLatency,
      token_usage: aiResult.tokenUsage || null,
    });
  } catch (err) {
    console.error(`[${requestId}] Gemini Model Analysis Error:`, err);
    res.status(500).json({ error: err.message || "An error occurred.", requestId });
  }
});

app.get("/api/stats", (req, res) => {
  res.json(db.getStats());
});

app.get("/api/queue", (req, res) => {
  const limit = parseInt(req.query.limit) || 100;
  const history = db.getTriageHistory(limit);
  res.json({ entries: history, total: history.length });
});

app.post("/api/evaluate", async (req, res) => {
  try {
    const { maxCases } = req.body || {};
    const evalResult = await runEvaluation({ maxCases: maxCases || 40 });
    res.json(evalResult);
  } catch (err) {
    res.status(500).json({ error: "Evaluation error", details: err.message });
  }
});

app.get("/api/health", async (req, res) => {
  const geminiPing = await pingGemini();
  res.json({
    status: "operational",
    timestamp: new Date().toISOString(),
    backend: "sqlite_persistent_backend",
    gemini: geminiPing,
    environment: process.env.NODE_ENV || "development",
  });
});

app.use((req, res) => {
  res.status(404).json({ error: "Endpoint not found." });
});

app.use((err, req, res, next) => {
  console.error("Unhandled error:", err);
  res.status(500).json({ error: "Internal server error." });
});

app.listen(PORT, "0.0.0.0", () => {
  console.log(`
╔══════════════════════════════════════════════╗
║          FRONTLINE AI — Backend Server        ║
║   AI-Powered Customer Support Triage          ║
╚══════════════════════════════════════════════╝
🚀 Server running on http://localhost:${PORT} and Network 0.0.0.0:${PORT}
📊 API: http://localhost:${PORT}/api
🔑 Gemini API key: ${process.env.GEMINI_API_KEY ? "✅ Configured" : "❌ NOT SET"}
  `);
});
