import "dotenv/config";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import { v4 as uuidv4 } from "uuid";

import { analyzeMessage, pingGemini } from "../frontline-ai/backend/ai/gemini.js";
import { runGuardrails, sanitizeAIOutput } from "../frontline-ai/backend/guardrails/guardrails.js";
import { applyDecisionRules } from "../frontline-ai/backend/decision/decisionEngine.js";
import { runEvaluation } from "../frontline-ai/backend/evaluation/evaluator.js";
import { db } from "../frontline-ai/backend/database.js";

const app = express();

app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: "*", credentials: true }));
app.use(express.json({ limit: "1mb" }));

/**
 * Real-Time Gemini AI Triage Endpoint
 * All analysis is dynamically generated by Google Gemini 2.0 Flash LLM.
 */
app.post("/api/analyze", async (req, res) => {
  const requestId = uuidv4();
  const requestStart = Date.now();

  try {
    const { message } = req.body;

    if (!message || typeof message !== "string") {
      return res.status(400).json({ error: "Invalid request. 'message' field is required.", requestId });
    }

    // Layer 1 & 2: Pre-AI Security Guardrails
    const guardrailResult = runGuardrails(message);

    if (guardrailResult.blocked && !guardrailResult.adversarial) {
      const blockedDecision = {
        category: "OUT_OF_SCOPE",
        priority: "P3",
        summary: guardrailResult.reason || "Message blocked by guardrails.",
        suggested_action: "Review guardrail flags and respond appropriately.",
        needs_human: true,
        confidence: 0.1,
        language: "Unknown",
        sentiment: "NEUTRAL",
        risk_level: guardrailResult.risk,
        issues: [],
        is_multi_issue: false,
        is_adversarial: guardrailResult.adversarial,
        is_out_of_scope: true,
        escalation_reason: guardrailResult.reason,
        reasoning_summary: `Blocked by guardrail: ${guardrailResult.flags.join(", ")}`,
        outcome: "BLOCKED_UNSAFE",
        outcome_label: "Blocked — Safety Check Failed",
        decision_overrides: [],
        decision_rules_applied: ["GUARDRAIL_BLOCK"],
      };

      const totalLatency = Date.now() - requestStart;
      db.insertTriage({ id: requestId, timestamp: new Date().toISOString(), message, decision: blockedDecision, latency_ms: totalLatency });

      return res.json({
        requestId,
        decision: blockedDecision,
        guardrails: { blocked: guardrailResult.blocked, adversarial: guardrailResult.adversarial, risk: guardrailResult.risk, flags: guardrailResult.flags },
        latency_ms: totalLatency,
        token_usage: null,
      });
    }

    // Layer 3: Dynamic Google Gemini 2.0 Flash LLM Analysis
    const messageToAnalyze = guardrailResult.sanitized || message;
    const aiResult = await analyzeMessage(messageToAnalyze);

    // Layer 4 & 5: Sanitization and Business Decision Engine Policy Verification
    const sanitizedDecision = sanitizeAIOutput(aiResult.decision);
    if (guardrailResult.adversarial) {
      sanitizedDecision.is_adversarial = true;
    }

    const finalDecision = applyDecisionRules(sanitizedDecision, guardrailResult);
    const totalLatency = Date.now() - requestStart;

    // Persist real AI decision into SQLite Database
    db.insertTriage({
      id: requestId,
      timestamp: new Date().toISOString(),
      message,
      decision: finalDecision,
      latency_ms: totalLatency,
    });

    res.json({
      requestId,
      decision: finalDecision,
      guardrails: {
        blocked: guardrailResult.blocked,
        adversarial: guardrailResult.adversarial,
        risk: guardrailResult.risk,
        flags: guardrailResult.flags,
      },
      latency_ms: totalLatency,
      token_usage: aiResult.tokenUsage || null,
    });
  } catch (err) {
    console.error(`[${requestId}] Gemini Model Analysis Error:`, err);
    res.status(500).json({ error: err.message || "Gemini AI model execution failed.", requestId });
  }
});

app.get("/api/health", async (req, res) => {
  const geminiPing = await pingGemini();
  res.json({
    status: "operational",
    timestamp: new Date().toISOString(),
    backend: "sqlite_persistent_backend",
    gemini: geminiPing,
    environment: process.env.NODE_ENV || "production",
  });
});

app.get("/api/stats", (req, res) => {
  res.json(db.getStats());
});

app.get("/api/queue", (req, res) => {
  const history = db.getTriageHistory(100);
  res.json({ entries: history, total: history.length });
});

app.post("/api/evaluate", async (req, res) => {
  try {
    const { maxCases } = req.body || {};
    const evalResult = await runEvaluation({ maxCases: maxCases || 40 });
    res.json(evalResult);
  } catch (err) {
    res.status(500).json({ error: "Evaluation error", details: err.message });
  }
});

export default app;
